### PR TITLE
Chore: DApplication::loadTranslator documentation update

### PR DESCRIPTION
**Pull request by RigoLigoRLC**
Updated English docs and added definition of APPNAME.

### CODE REVIEW

**Comment by RigoLigoRLC** [comment]
Updated commit to comply with commit standard.

**Review by deepinAdmin — COMMENTED** [review]
Patch Set 3: Code-Review+1

**Review by deepinAdmin — COMMENTED** [review]
Patch Set 3: Code-Review+1

**Review by deepinAdmin — APPROVED** [review]
Approve merged, Will be auto merge

**Review by deepinAdmin — APPROVED** [review]
Approve merged, Will be auto merge

**Review by deepinAdmin — COMMENTED** [review]
Patch Set 1:

代码注释率

**Review by deepinAdmin — COMMENTED** [review]
Patch Set 1: Code-Review-2

(1 comment)

commit check error!

**Review by deepinAdmin — COMMENTED** [review]
Patch Set 1: -Code-Review

cppcheck success!

**Pull request merged**
