### PR TITLE
feat: sidebar widget with blur widget behind

### PR DESCRIPTION
**Pull request by kegechen**

### CODE REVIEW

**Comment by kegechen** [comment]
image

**Review by 18202781743 — APPROVED** [review]

**Review by FeiWang1119 — APPROVED** [review]

**Review by zccrs — APPROVED** [review]

**Comment by kegechen** [comment]
fix:
- https://github.com/linuxdeepin/developer-center/issues/7150
- https://github.com/linuxdeepin/developer-center/issues/7148

**Pull request merged**
